"""Contrato consumido por el adaptador HTTP de operaciones."""

from typing import Any, Protocol


class CasosUsoOperaciones(Protocol):
    """Superficie pública; la implementación transaccional se compone en Core."""

    async def crear_proveedor(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def listar_proveedores(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def obtener_proveedor(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def actualizar_proveedor(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any]: ...
    async def crear_repuesto(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def listar_repuestos(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def obtener_repuesto(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def actualizar_repuesto(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any]: ...
    async def entrada_stock(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def ajustar_stock(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def listar_movimientos(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def crear_metodo_pago(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def listar_metodos_pago(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def actualizar_metodo_pago(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any]: ...
    async def crear_orden(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def listar_ordenes(
        self, *args: Any, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    async def obtener_orden(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def actualizar_orden(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def transicionar(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def reabrir_garantia(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def agregar_servicio(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def retirar_servicio(self, *args: Any, **kwargs: Any) -> None: ...
    async def agregar_repuesto_orden(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any]: ...
    async def retirar_repuesto_orden(self, *args: Any, **kwargs: Any) -> None: ...
    async def aplicar_descuento(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def registrar_pago(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def listar_pagos(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def anular_pago(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def historial(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
